theme: minima
title: Tech Geek - The Coder
author: GitHub User
email: arunchauhan2319@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coder | Digital Marketer | Writer on Linkedin | Problem Solver on Hackerrank
  

# social links
twitter_username: imarun_chauhan
github_username:  iamarunchauhan

show_excerpts: true # set to false to remove excerpts on the homepage
